- docs/slides/multi-cloud/Nomad_Preemption.md
- docs/slides/multi-cloud/index.html
- docs/slides/multi-cloud/nomad_concepts_arch.md
Checking in the first public version of the Nomad Concepts and Architecture slides, along with some deeper slides on preemption.
> Slides for Nomad Concepts and Architecture

- instruqt-tracks/nomad-basics/run-first-job/check-nomad-server
- instruqt-tracks/nomad-basics/run-first-job/solve-nomad-server
- instruqt-tracks/nomad-basics/run-nomad-agent/check-nomad-server
- instruqt-tracks/nomad-basics/run-nomad-agent/solve-nomad-server
- instruqt-tracks/nomad-basics/track.yml
- instruqt-tracks/nomad-basics/use-nomad-http-api/check-nomad-server
- instruqt-tracks/nomad-basics/use-nomad-http-api/solve-nomad-server
yaml and check scripts for the Nomad basics track.
> Nomad Basics track

- docs/slides/multi-cloud/nomad-oss/nomad-3-interacting-with-nomad.md
Nomad Chapter 3 slides for walking through Instruqt
> Initial checkin for Nomad Chapter 3

- docs/slides/multi-cloud/nomad-enterprise/index.html
- docs/slides/multi-cloud/nomad-enterprise/nomad-job-placement.html
- docs/slides/multi-cloud/nomad-enterprise/nomad-job-placement.md
These slides from Chris cover job placement including constraints, affinity, and spread. They also cover variable interpolation.  I have done some editing on them.
> Chrisd 2020121

- instruqt-tracks/nomad-governance/namespaces-and-resource-quotas/setup-nomad-server-1
- instruqt-tracks/nomad-governance/preempt-jobs/check-nomad-server-1
- instruqt-tracks/nomad-governance/preempt-jobs/setup-nomad-server-1
- instruqt-tracks/nomad-governance/preempt-jobs/solve-nomad-server-1
- instruqt-tracks/nomad-governance/run-nomad-jobs-1/setup-nomad-server-1
- instruqt-tracks/nomad-governance/track.yml
added preemption challenge to end of governance track
> completed nomad governance track

- docs/slides/multi-cloud/advanced-nomad/nomad-0.md
- docs/slides/multi-cloud/advanced-nomad/nomad-1.5-job-update-strategies.html
- docs/slides/multi-cloud/advanced-nomad/nomad-1.5-job-update-strategies.md
- docs/slides/multi-cloud/advanced-nomad/nomad-5-governance.md
For now, the Nomad Job Update Strategies are chapter 1.5.
Later, I will renumber chapters.
> finished gov slides; placeholder for updates

- docs/slides/multi-cloud/advanced-nomad/nomad-stateful-workloads.md
- instruqt-tracks/nomad-host-volumes/config.yml
- instruqt-tracks/nomad-host-volumes/configure-host-volume/check-nomad-server-1
- instruqt-tracks/nomad-host-volumes/configure-host-volume/setup-nomad-server-1
- instruqt-tracks/nomad-host-volumes/configure-host-volume/solve-nomad-server-1
- instruqt-tracks/nomad-host-volumes/track.yml
- instruqt-tracks/nomad-host-volumes/verify-nomad-cluster-health/check-nomad-server-1
- instruqt-tracks/nomad-host-volumes/verify-nomad-cluster-health/setup-nomad-client-1
- instruqt-tracks/nomad-host-volumes/verify-nomad-cluster-health/setup-nomad-client-2
- instruqt-tracks/nomad-host-volumes/verify-nomad-cluster-health/setup-nomad-client-3
- instruqt-tracks/nomad-host-volumes/verify-nomad-cluster-health/setup-nomad-server-1
- instruqt-tracks/nomad-host-volumes/verify-nomad-cluster-health/solve-nomad-server-1
- instruqt-tracks/nomad-update-strategies/deploy-the-jobs/check-nomad-server-1
- instruqt-tracks/nomad-update-strategies/track.yml
Begin a new nomad-host-volumes track based on https://learn.hashicorp.com/nomad/stateful-workloads/host-volumes
Also made a few minor fixes to the Job Update Strategies track such as changing "Nomad Enterprise" to "Nomad".
And made minor changes to one of the stateful workload slides.
> begin nomad-host-volumes track

- .circleci/config.yml
actually added CircleCI tests for 4 tracks.  I had neglected to add tests for the other Advanced Nomad Workshop tracks.
> add CircleCI tests for more tracks

- .circleci/config.yml
- instruqt-tracks/nomad-and-portworx/deploy-mysql/solve-cloud-client
- instruqt-tracks/nomad-and-portworx/install-portworx/check-cloud-client
- instruqt-tracks/nomad-and-portworx/install-portworx/solve-cloud-client
- instruqt-tracks/nomad-and-portworx/stop-and-restart-mysql/check-cloud-client
- instruqt-tracks/nomad-and-portworx/stop-and-restart-mysql/setup-cloud-client
- instruqt-tracks/nomad-and-portworx/stop-and-restart-mysql/solve-cloud-client
- instruqt-tracks/nomad-and-portworx/track.yml
- instruqt-tracks/nomad-and-portworx/verify-nomad-cluster-health/check-cloud-client
- instruqt-tracks/nomad-and-portworx/verify-nomad-cluster-health/solve-cloud-client
- instruqt-tracks/nomad-and-portworx/write-data/check-cloud-client
- instruqt-tracks/nomad-and-portworx/write-data/setup-cloud-client
- instruqt-tracks/nomad-and-portworx/write-data/solve-cloud-client
- instruqt-tracks/nomad-host-volumes/stop-and-restart-job/check-nomad-server-1
- instruqt-tracks/nomad-host-volumes/track.yml
finished nomad with portworx track
> finish nomad with portworx track

- instruqt-tracks/nomad-acls/track.yml
- instruqt-tracks/nomad-governance/track.yml
- instruqt-tracks/nomad-multi-server-cluster/track.yml
- instruqt-tracks/nomad-update-strategies/track.yml
I shortened the teasers about verifying the health of the Nomad/Consul clusters in multiple Nomad tracks.
> shortened some teasers

- instruqt-tracks/nomad-acls/track.yml
- instruqt-tracks/nomad-and-portworx/track.yml
- instruqt-tracks/nomad-basics/track.yml
- instruqt-tracks/nomad-consul-connect/track.yml
- instruqt-tracks/nomad-governance/track.yml
- instruqt-tracks/nomad-host-volumes/track.yml
- instruqt-tracks/nomad-integration-with-vault/track.yml
- instruqt-tracks/nomad-job-placement/track.yml
- instruqt-tracks/nomad-monitoring/track.yml
- instruqt-tracks/nomad-multi-server-cluster/track.yml
- instruqt-tracks/nomad-on-windows/track.yml
- instruqt-tracks/nomad-simple-cluster/track.yml
- instruqt-tracks/nomad-update-strategies/track.yml
add track timers to all Nomad Workshop tracks.
> add track timers

- docs/slides/multi-cloud/advanced-nomad/nomad-stateful-workloads.md
- instruqt-tracks/nomad-and-csi-plugins-gcp/track.yml
- instruqt-tracks/nomad-and-portworx/track.yml
- instruqt-tracks/nomad-host-volumes/track.yml
Update stateful workload slides
> Finalize csi plugin gcp track

- docs/slides/multi-cloud/advanced-nomad/nomad-0.md
- docs/slides/multi-cloud/advanced-nomad/nomad-stateful-workloads.md
- instruqt-tracks/nomad-and-csi-plugins-gcp/track.yml
also update description and add link for the Nomad CSI (GCP) track.
> Update stateful workload slides

- docs/slides/multi-cloud/advanced-nomad/nomad-0.md
- docs/slides/multi-cloud/nomad-oss/nomad-0.md
- docs/slides/multi-cloud/nomad-oss/nomad-2.md
change "Secrets Management Experience" on Introduction slides to "Orchestration Experience"
> fix Introductions slides

- instruqt-tracks/nomad-governance/config.yml
- instruqt-tracks/nomad-governance/nomad-acls/setup-nomad-server-1
- instruqt-tracks/nomad-governance/nomad-auditing/check-nomad-client-1
- instruqt-tracks/nomad-governance/nomad-auditing/check-nomad-client-2
- instruqt-tracks/nomad-governance/nomad-auditing/check-nomad-client-3
- instruqt-tracks/nomad-governance/nomad-auditing/check-nomad-server-1
- instruqt-tracks/nomad-governance/nomad-auditing/setup-nomad-client-1
- instruqt-tracks/nomad-governance/nomad-auditing/setup-nomad-client-2
- instruqt-tracks/nomad-governance/nomad-auditing/setup-nomad-client-3
- instruqt-tracks/nomad-governance/nomad-auditing/setup-nomad-server-1
- instruqt-tracks/nomad-governance/nomad-auditing/solve-nomad-server-1
- instruqt-tracks/nomad-governance/track.yml
Updated Nomad Governance Instruqt track to 0.12.1 and also added first challenge on Audit Logging.
> Nomad governance 12

- instruqt-tracks/nomad-governance/run-nomad-jobs-2/check-nomad-server-1
- instruqt-tracks/nomad-governance/run-nomad-jobs-2/solve-nomad-server-1
- instruqt-tracks/nomad-governance/track.yml
The Nomad Enterprise Governance track now covers all Nomad Enterprise Governance and Policy features.
> add cross-namespace query

- instruqt-tracks/nomad-basics/run-first-job/solve-nomad-server
- instruqt-tracks/nomad-basics/run-nomad-agent/solve-nomad-server
- instruqt-tracks/nomad-basics/track.yml
- instruqt-tracks/nomad-basics/use-nomad-http-api/solve-nomad-server
add some sleeps to avoid isssues in CircleCI tests.
> improve scripts

- instructor-guides/advanced_nomad_INSTRUCTOR_GUIDE.md
- instructor-guides/intro_to_nomad_INSTRUCTOR_GUIDE.md
document configuration of Instruqt pools
> document Instruqt pools

- .circleci/config.yml
> add circleci test for nomad-federation

- instruqt-tracks/nomad-multi-region-federation/track.yml
Update track description to refer to two learn guides the track is based on.
> update track description

- instruqt-tracks/nomad-multi-region-federation/config.yml
- instruqt-tracks/nomad-multi-region-federation/track.yml
update Federation track to Nomad Enterprise 0.12.4
> update to Nomad 0.12.4

- instruqt-tracks/nomad-acls/track.yml
- instruqt-tracks/nomad-and-portworx/track.yml
- instruqt-tracks/nomad-basics/track.yml
- instruqt-tracks/nomad-host-volumes/track.yml
- instruqt-tracks/nomad-job-placement/track.yml
- instruqt-tracks/nomad-multi-region-federation/track.yml
- instruqt-tracks/nomad-simple-cluster/track.yml
- instruqt-tracks/nomad-update-strategies/track.yml
give each Nomad Instruqt track at least 60 minutes
Also fix a typo in the Update Strategies track
> extend track times to 60+ minutes

- instruqt-tracks/nomad-acls/config.yml
- instruqt-tracks/nomad-and-csi-plugins-gcp/verify-nomad-cluster-health/setup-cloud-client
- instruqt-tracks/nomad-and-portworx/verify-nomad-cluster-health/setup-cloud-client
- instruqt-tracks/nomad-basics/config.yml
- instruqt-tracks/nomad-consul-connect/config.yml
- instruqt-tracks/nomad-governance/config.yml
- instruqt-tracks/nomad-host-volumes/config.yml
- instruqt-tracks/nomad-integration-with-vault/config.yml
- instruqt-tracks/nomad-job-placement/config.yml
- instruqt-tracks/nomad-monitoring/config.yml
- instruqt-tracks/nomad-multi-region-federation/config.yml
- instruqt-tracks/nomad-multi-server-cluster/config.yml
- instruqt-tracks/nomad-on-windows/verify-nomad-cluster-health/setup-cloud-client
- instruqt-tracks/nomad-simple-cluster/config.yml
- instruqt-tracks/nomad-update-strategies/config.yml
Update to newer hashistack-0-9-1 and hashistack-enterprise-0-9-1 images that use Nomad 1.0.0, Consul 1.9.0, Vault 1.6.0, and Terraform 0.14.1
> update to Nomad 1.0.0

- .circleci/config.yml
- instruqt-tracks/nomad-and-csi-plugins-gcp/deploy-gcepd-driver/setup-cloud-client
- instruqt-tracks/nomad-and-csi-plugins-gcp/deploy-mysql/setup-cloud-client
- instruqt-tracks/nomad-and-csi-plugins-gcp/track.yml
- instruqt-tracks/nomad-and-portworx/deploy-mysql/setup-cloud-client
- instruqt-tracks/nomad-and-portworx/install-portworx/setup-cloud-client
- instruqt-tracks/nomad-and-portworx/track.yml
- instruqt-tracks/nomad-and-portworx/verify-nomad-cluster-health/setup-cloud-client
- instruqt-tracks/nomad-host-volumes/deploy-mysql/setup-nomad-server-1
- instruqt-tracks/nomad-host-volumes/track.yml
- instruqt-tracks/nomad-update-strategies/blue-green-deployment/setup-nomad-server-1
- instruqt-tracks/nomad-update-strategies/canary-deployment/setup-nomad-server-1
- instruqt-tracks/nomad-update-strategies/deploy-the-jobs/setup-nomad-server-1
- instruqt-tracks/nomad-update-strategies/rolling-update/setup-nomad-server-1
also removed portworx track from CircleCI testing since I cannot yet get it to work.
The portworx.nomad job is failing. I did enable volumes in docker config of nomad clients which got past one problem, but logs show errors.
> more hcl2 fixes and portworx volumes

- docs/slides/multi-cloud/advanced-nomad/nomad-autoscaler.md
- docs/slides/multi-cloud/advanced-nomad/nomad-end.md
- docs/slides/multi-cloud/advanced-nomad/nomad-governance.md
- docs/slides/multi-cloud/advanced-nomad/nomad-stateful-workloads.md
Update slides to cover 1.0.0 release including fact that namespaces are now OSS and to reflect new things added to Nomad Autoscaling including Horizontal Cluster AS for Azure and Dynamic Application Sizing.
> update slides for 1.0.0 and new Autoscaling features

- .circleci/config.yml
re-naming master branch to main.  This PR updates CircleCI tests
> master to main

- docs/slides/multi-cloud/nomad-oss/nomad-1.md
- docs/slides/multi-cloud/nomad-oss/nomad-2.md
Added the cloud solutions supported by the Autoscaler now.
Added the Dynamic Application Sizing Enterprise feature
Fixed a typo in the Scheduler section
> Updated Some Typos and added some new information

- docs/slides/korean/multi-cloud/nomad-oss/index.html
- docs/slides/korean/multi-cloud/nomad-oss/nomad-0.html
- docs/slides/korean/multi-cloud/nomad-oss/nomad-0.md
- docs/slides/korean/multi-cloud/nomad-oss/nomad-1.html
- docs/slides/korean/multi-cloud/nomad-oss/nomad-1.md
- docs/slides/korean/multi-cloud/nomad-oss/nomad-2.html
- docs/slides/korean/multi-cloud/nomad-oss/nomad-2.md
- docs/slides/korean/multi-cloud/nomad-oss/nomad-3.html
- docs/slides/korean/multi-cloud/nomad-oss/nomad-3.md
- docs/slides/korean/multi-cloud/nomad-oss/nomad-4.html
- docs/slides/korean/multi-cloud/nomad-oss/nomad-4.md
- docs/slides/korean/multi-cloud/nomad-oss/nomad-5.html
- docs/slides/korean/multi-cloud/nomad-oss/nomad-5.md
- docs/slides/korean/multi-cloud/nomad-oss/nomad-6.html
- docs/slides/korean/multi-cloud/nomad-oss/nomad-6.md
- docs/slides/korean/multi-cloud/nomad-oss/nomad-7.html
- docs/slides/korean/multi-cloud/nomad-oss/nomad-7.md
- docs/slides/korean/multi-cloud/nomad-oss/nomad-end.html
- docs/slides/korean/multi-cloud/nomad-oss/nomad-end.md
Added local slides for workshops in Korea
> Korean slide update

- docs/slides/multi-cloud/advanced-nomad/nomad-stateful-workloads.md
remove extra ] from nomad-stateful-workloads.md slide
> remove ] from slide

- instruqt-tracks/nomad-governance/verify-nomad-cluster-health/setup-nomad-client-1
- instruqt-tracks/nomad-governance/verify-nomad-cluster-health/setup-nomad-client-2
- instruqt-tracks/nomad-governance/verify-nomad-cluster-health/setup-nomad-client-3
- instruqt-tracks/nomad-governance/verify-nomad-cluster-health/setup-nomad-server-1
Merge after confirmation from @gitrgoliveira that a second test run of this track succeeded.
> Delay setup scripts until after Instruqt bootstrap completes (see note before merging)

- instruqt-tracks/nomad-host-volumes/track.yml
> Fixes spelling

- instruqt-tracks/nomad-multi-region-federation/simulate-failed-deployment/setup-nomad-server-1-west
Currently the variable is not being populated in the script. This fixes it.
> Updates template environment variable
