hashicorp/field-workshops-nomad

- instruqt-tracks/nomad-governance/config.yml
- instruqt-tracks/nomad-governance/track.yml
- instruqt-tracks/nomad-governance/verify-nomad-cluster-health/check-nomad-client-1
- instruqt-tracks/nomad-governance/verify-nomad-cluster-health/check-nomad-client-2
- instruqt-tracks/nomad-governance/verify-nomad-cluster-health/check-nomad-client-3
- instruqt-tracks/nomad-governance/verify-nomad-cluster-health/check-nomad-server-1
- instruqt-tracks/nomad-governance/verify-nomad-cluster-health/setup-nomad-client-1
- instruqt-tracks/nomad-governance/verify-nomad-cluster-health/setup-nomad-client-2
- instruqt-tracks/nomad-governance/verify-nomad-cluster-health/setup-nomad-client-3
- instruqt-tracks/nomad-governance/verify-nomad-cluster-health/setup-nomad-server-1
- instruqt-tracks/nomad-governance/verify-nomad-cluster-health/solve-nomad-client-1
- instruqt-tracks/nomad-governance/verify-nomad-cluster-health/solve-nomad-client-2
- instruqt-tracks/nomad-governance/verify-nomad-cluster-health/solve-nomad-client-3
- instruqt-tracks/nomad-governance/verify-nomad-cluster-health/solve-nomad-server-1
begin a Nomad Governance Instruqt track that can also be used as a template for other tracks that need Nomad Enterprise.
It creates a single Nomad/Consul server and 3 Nomad/Consul clients, running Nomad Enterprise 0.10.4 and Consul OSS 1.7.0.
The GCP image used is instruqt-hashicorp/nomad-ent-0-10-4
> begin nomad-governance track

- instruqt-tracks/nomad-governance/run-nomad-jobs-1/setup-nomad-server-1
- instruqt-tracks/nomad-governance/run-nomad-jobs-2/check-nomad-server-1
- instruqt-tracks/nomad-governance/run-nomad-jobs-2/setup-nomad-server-1
- instruqt-tracks/nomad-governance/run-nomad-jobs-2/solve-nomad-server-1
- instruqt-tracks/nomad-governance/track.yml
Completed challenge that runs jobs affected by resource quotas
Also gave each job a priority of "40" and set job type to "service" (which is default), but I wanted to make it explicit for use with Preemption.
I checked that enabling Premption for service and batch jobs does not require restarting the Nomad server or clients.  It only requires a curl call against the Nomad API https://nomadproject.io/api-docs/operator/#update-scheduler-configuration.
So, last challenge that Patrick Gryzan will add can simply enable preemption and then run a job big enough that would preempt one of the other jobs.
> Add quota runs

- instruqt-tracks/nomad-update-strategies/blue-green-deployment/check-nomad-server-1
- instruqt-tracks/nomad-update-strategies/blue-green-deployment/setup-nomad-server-1
- instruqt-tracks/nomad-update-strategies/blue-green-deployment/solve-nomad-server-1
- instruqt-tracks/nomad-update-strategies/canary-deployment/check-nomad-server-1
- instruqt-tracks/nomad-update-strategies/canary-deployment/setup-nomad-server-1
- instruqt-tracks/nomad-update-strategies/canary-deployment/solve-nomad-server-1
- instruqt-tracks/nomad-update-strategies/config.yml
- instruqt-tracks/nomad-update-strategies/deploy-the-jobs/check-nomad-server-1
- instruqt-tracks/nomad-update-strategies/deploy-the-jobs/setup-nomad-server-1
- instruqt-tracks/nomad-update-strategies/deploy-the-jobs/solve-nomad-server-1
- instruqt-tracks/nomad-update-strategies/rolling-update/check-nomad-server-1
- instruqt-tracks/nomad-update-strategies/rolling-update/setup-nomad-server-1
- instruqt-tracks/nomad-update-strategies/rolling-update/solve-nomad-server-1
- instruqt-tracks/nomad-update-strategies/track.yml
- instruqt-tracks/nomad-update-strategies/verify-nomad-cluster-health/check-nomad-server-1
- instruqt-tracks/nomad-update-strategies/verify-nomad-cluster-health/setup-nomad-client-1
- instruqt-tracks/nomad-update-strategies/verify-nomad-cluster-health/setup-nomad-client-2
- instruqt-tracks/nomad-update-strategies/verify-nomad-cluster-health/setup-nomad-client-3
- instruqt-tracks/nomad-update-strategies/verify-nomad-cluster-health/setup-nomad-server-1
- instruqt-tracks/nomad-update-strategies/verify-nomad-cluster-health/solve-nomad-server-1
Added track https://play.instruqt.com/hashicorp/tracks/nomad-update-strategies that implements https://learn.hashicorp.com/nomad/update-strategies.  It uses the chat-app appliction from Guy Barrows and Lance Haig: https://github.com/GuyBarros/anonymouse-realtime-chat-app with docker images in https://hub.docker.com/r/lhaig/anon-app.
This version uses Fabio, but it does not seem compatible with the sockets.io library that the app uses.  I will try using nginx instead of Fabio in a different branch.
> Add update strategies track

- instruqt-tracks/nomad-update-strategies/deploy-the-jobs/check-nomad-server-1
- instruqt-tracks/nomad-update-strategies/deploy-the-jobs/setup-nomad-server-1
- instruqt-tracks/nomad-update-strategies/deploy-the-jobs/solve-nomad-server-1
- instruqt-tracks/nomad-update-strategies/track.yml
Switched "Nomad Job Update Strategies" track to use NGINX instead of Fabio to leverage the former's sticky sessions. The chat app behaves better with NGINX.
> switch to nginx

- instruqt-tracks/nomad-integration-with-vault/config.yml
- instruqt-tracks/nomad-integration-with-vault/track.yml
This now uses the GCP image instruqt-hashicorp/hashistack-0-5-1 which uses Nomad 0.10.4, Consul 1.7.1, and Nomad 1.3.2.  I updated this to test fix to Consul 1.7 (in 1.7.1) which had prevented consul services from displaying in the Consul UI if Consul Connect was not enabled on all the Consul clients.  The fix did work.  Having this track on newer version of Nomad and Consul is fringe benefit.  It had been using Nomad 0.10.2, Consul 1.6.2, and Vault 1.3.0
I also expanded descriptions of what to look for in `nomad status` commands in track.yml to include verifying that each job has 1 healthy allocation.
> update to Nomad 0.10.4, Consul 1.7.1

- .circleci/config.yml
- instruqt-tracks/nomad-and-portworx/install-portworx/setup-cloud-client
- instruqt-tracks/nomad-and-portworx/track.yml
- instruqt-tracks/nomad-and-portworx/verify-nomad-cluster-health/setup-cloud-client
- instruqt-tracks/nomad-consul-connect/config.yml
- instruqt-tracks/nomad-consul-connect/nomad-and-consul-connect/check-nomad-server-1
- instruqt-tracks/nomad-consul-connect/nomad-and-consul-connect/setup-nomad-server-1
- instruqt-tracks/nomad-consul-connect/nomad-and-consul-connect/solve-nomad-server-1
- instruqt-tracks/nomad-consul-connect/track.yml
- instruqt-tracks/nomad-consul-connect/verify-nomad-cluster-health/check-nomad-server-1
- instruqt-tracks/nomad-consul-connect/verify-nomad-cluster-health/setup-nomad-client-1
- instruqt-tracks/nomad-consul-connect/verify-nomad-cluster-health/setup-nomad-client-2
- instruqt-tracks/nomad-consul-connect/verify-nomad-cluster-health/setup-nomad-server-1
- instruqt-tracks/nomad-consul-connect/verify-nomad-cluster-health/solve-nomad-server-1
- instruqt-tracks/nomad-job-placement/track.yml
- instruqt-tracks/nomad-job-placement/verify-nomad-cluster-health/setup-nomad-client-1
- instruqt-tracks/nomad-job-placement/verify-nomad-cluster-health/setup-nomad-client-3
- instruqt-tracks/nomad-job-placement/verify-nomad-cluster-health/setup-nomad-server-1
- instruqt-tracks/nomad-multi-server-cluster/track.yml
- instruqt-tracks/nomad-update-strategies/track.yml
- instruqt-tracks/nomad-update-strategies/verify-nomad-cluster-health/check-nomad-server-1
I split out the Nomad-Consul Connect challenge which is at the end of the nomad-multi-server-cluster track into a new track called nomad-consul-connect.  I left the original challenge in place.
My reason for creating the new track was to make it easier for SEs to demo Nomad integration with Consul Connect since they can now use the new track without having to step through the other two challenges which focused on configuring the Nomad/Consul clusters.
This PR also includes some fixes for typos and extra comments in some scripts.
> create separate nomad-consul-connect track

- instruqt-tracks/nomad-basics/config.yml
- instruqt-tracks/nomad-basics/track.yml
- instruqt-tracks/nomad-monitoring/add-web-server/check-nomad-server
- instruqt-tracks/nomad-monitoring/add-web-server/solve-nomad-server
- instruqt-tracks/nomad-monitoring/config.yml
- instruqt-tracks/nomad-monitoring/track.yml
- instruqt-tracks/nomad-multi-server-cluster/config.yml
- instruqt-tracks/nomad-multi-server-cluster/track.yml
- instruqt-tracks/nomad-simple-cluster/config.yml
- instruqt-tracks/nomad-simple-cluster/modifying-a-job/solve-nomad-server
- instruqt-tracks/nomad-simple-cluster/run-your-first-job/solve-nomad-server
- instruqt-tracks/nomad-simple-cluster/track.yml
I updated the image used by the 4 Instruqt tracks of the Intro to Nomad workshop to use Nomad 0.11.2.
I also fixed various links in the 4 tracks, especially in nomad-monitoring.
In that track, I also removed an unnecessary instruction to run the prometheus job a third time.
> update to Nomad 0.11.2 in Intro Nomad workshop

- instruqt-tracks/nomad-consul-connect/config.yml
- instruqt-tracks/nomad-consul-connect/track.yml
Created new VM image, hashistack-0-6-3 with Nomad 0.11.3 and Consul 1.7.4 so I could test whether unavailability of allocation logs in Nomad UI is still a problem in 0.11.3.  Sadly, it still is.
> use 0.11.3 for Consul Connect track

- instruqt-tracks/nomad-monitoring/track.yml
- instruqt-tracks/nomad-simple-cluster/track.yml
The Nomad Monitoring track had a total timelimit of 30 minutes, but some people needed more. I doubled to 60 minutes.
I also removed references to examining allocation logs in the Nomad UI from the Nomad Simple Cluster track because that does not work inside Instruqt.
> extend monitoring track, remove UI logs

- instruqt-tracks/nomad-multi-region-federation/track.yml
correction to the notes in the Multi-Region Nomad Deployments challenge to direct the user to the proper directory for finding the job file to inspect
> fix challenge notes for Multi-Region Nomad Deployments challenge

- docs/slides/multi-cloud/advanced-nomad/nomad-autoscaler.md
- docs/slides/multi-cloud/advanced-nomad/nomad-enterprise-platform.md
- docs/slides/multi-cloud/advanced-nomad/nomad-governance.md
- docs/slides/multi-cloud/advanced-nomad/nomad-job-update-strategies.md
- docs/slides/multi-cloud/advanced-nomad/nomad-security.md
- docs/slides/multi-cloud/advanced-nomad/nomad-stateful-workloads.md
- instruqt-tracks/nomad-and-csi-plugins-gcp/track.yml
- instruqt-tracks/nomad-and-portworx/install-portworx/setup-cloud-client
- instruqt-tracks/nomad-and-portworx/track.yml
- instruqt-tracks/nomad-basics/track.yml
- instruqt-tracks/nomad-consul-connect/track.yml
- instruqt-tracks/nomad-governance/run-nomad-jobs-1/setup-nomad-server-1
- instruqt-tracks/nomad-governance/track.yml
- instruqt-tracks/nomad-host-volumes/track.yml
- instruqt-tracks/nomad-job-placement/track.yml
- instruqt-tracks/nomad-monitoring/track.yml
- instruqt-tracks/nomad-multi-region-federation/multi-region-deployments/setup-nomad-server-1-east
- instruqt-tracks/nomad-multi-region-federation/multi-region-deployments/setup-nomad-server-1-west
- instruqt-tracks/nomad-multi-region-federation/simulate-failed-deployment/setup-nomad-server-1-east
- instruqt-tracks/nomad-multi-region-federation/simulate-failed-deployment/setup-nomad-server-1-west
- instruqt-tracks/nomad-multi-region-federation/track.yml
- instruqt-tracks/nomad-update-strategies/track.yml
Fixes for various issues noticed during the 9/15 Advanced Nomad Workshop:
1. Update all learn.hashicorp.com links to use "tutorials"
2. Remove "stagger" from jobs since is only used for system jobs.
3. Remove link to Traefik logo which is no longer valid. (and I could not find suitable replacement)
4. Remove 5th bullet from slide 74
5. Change second source to strategy in slide 101
6. Change "pomotes" to "promotes" in slide 107
7. Change "enteprise" to "enterprise" in slide 117 and add a period.
8. Fix repeated references to client1 to be client1, client2, client3
> fixes for issues noticed in 9/15 workshop

- instruqt-tracks/nomad-multi-region-federation/track.yml
Since the command I gave did not include `-purge`, it should not be mentioned in the paragraph before.
I already had text after the command indicating that `-purge` could be added if desired.
The change makes it more consistent.
> remove -purge from stop command

- instruqt-tracks/nomad-and-csi-plugins-gcp/deploy-mysql/setup-cloud-client
- instruqt-tracks/nomad-and-portworx/deploy-mysql/setup-cloud-client
- instruqt-tracks/nomad-governance/run-nomad-jobs-1/setup-nomad-server-1
- instruqt-tracks/nomad-host-volumes/deploy-mysql/setup-nomad-server-1
fixing some hcl2 parsing issues related to use of `=` when setting `env`.  Had to remove it.
> fix some hcl2 parsing issues

- instruqt-tracks/nomad-and-csi-plugins-gcp/track.yml
- instruqt-tracks/nomad-and-portworx/install-portworx/setup-cloud-client
- instruqt-tracks/nomad-and-portworx/track.yml
- instruqt-tracks/nomad-and-portworx/verify-nomad-cluster-health/setup-cloud-client
- instruqt-tracks/nomad-consul-connect/track.yml
- instruqt-tracks/nomad-governance/track.yml
- instruqt-tracks/nomad-host-volumes/track.yml
- instruqt-tracks/nomad-job-placement/track.yml
- instruqt-tracks/nomad-multi-region-federation/track.yml
- instruqt-tracks/nomad-on-windows/track.yml
- instruqt-tracks/nomad-update-strategies/track.yml
fixed nomad-and-portworx track by using newer docker image portworx/oci-monitor:2.6.2 instead of portworx/oci-monitor:2.4.0 and by changing VMs to use machine-type=n1-standard-4 instead of machine-type=n1-standard-2 since the newer version of the image requires VMs with 4 virtual CPUs.
I also changed Nomad client configuration files to use 
```
plugin "docker" {
config {
allow_privileged = true
volumes {
enabled      = true
}
}
}
```
> fix nomad-and-portworx

- .circleci/config.yml
- instruqt-tracks/nomad-multi-server-cluster/manual-clustering/solve-nomad-server-3
- instruqt-tracks/nomad-simple-cluster/run-the-server-and-clients/solve-nomad-server
Add nomad-and-portworx track back to CircleCI testing
Also add sleep to final solve challenges of nomad-simple-cluster and nomad-multi-server-clusters since the check scripts after the solve scripts are sometimes failing after having upgraded to Nomad 1.0.0
> Add portworx back to circleci

- instruqt-tracks/nomad-governance/namespaces-and-resource-quotas/setup-nomad-server-1
- instruqt-tracks/nomad-governance/nomad-acls/setup-nomad-client-1
- instruqt-tracks/nomad-governance/nomad-acls/setup-nomad-client-2
- instruqt-tracks/nomad-governance/nomad-acls/setup-nomad-client-3
- instruqt-tracks/nomad-governance/nomad-acls/setup-nomad-server-1
- instruqt-tracks/nomad-governance/run-nomad-jobs-1/setup-nomad-server-1
- instruqt-tracks/nomad-governance/run-nomad-jobs-2/setup-nomad-server-1
- instruqt-tracks/nomad-governance/sentinel-policies/setup-nomad-server-1
- instruqt-tracks/nomad-governance/track.yml
This PR updates network stanzas in Nomad job specs to avoid deprecation warnings that started appearing in Nomad 1.0.  This includes moving `network` stanzas out of `resources` to the `group` level, removing `mbits`, and replaceing `port_map` with `ports`.
> update network stanzas

- instruqt-tracks/nomad-acls/run-the-servers-and-clients/setup-nomad-server-3
- instruqt-tracks/nomad-acls/track.yml
- instruqt-tracks/nomad-basics/nomad-cli/setup-nomad-server
- instruqt-tracks/nomad-basics/track.yml
- instruqt-tracks/nomad-simple-cluster/track.yml
This updates the simple example/redis job spec used in 3 tracks to avoid deprecation warnings.  The tracks are:
1. https://play.instruqt.com/hashicorp/tracks/nomad-basics
2. https://play.instruqt.com/hashicorp/tracks/nomad-simple-cluster
3. https://play.instruqt.com/hashicorp/tracks/nomad-acls
In the second track, the job spec was already the one initialized by `nomad job. init --short`, but since that job is slightly different in Nomad 1.0.x, I made a change to track.yml to adjust where `count = 3` is added later.
I also made some minor edits in track.yml files of some of these tracks to clarify instructions.
Note that I also validated that https://play.instruqt.com/hashicorp/tracks/nomad-multi-server-cluster works correctly withoug any deprecation warnings, so it did not need any …
> update job spec 3 tracks

- instruqt-tracks/nomad-monitoring/fabio-and-prometheus-jobs/setup-nomad-server
- instruqt-tracks/nomad-monitoring/track.yml
Updateds the nomad-monitoring track to get rid of deprecation warnings that started showing up after track was updated to use Nomad 1.0
> update nomad-monitoring track

- instruqt-tracks/nomad-update-strategies/deploy-the-jobs/setup-nomad-server-1
- instruqt-tracks/nomad-update-strategies/track.yml
Update job specs in https://play.instruqt.com/hashicorp/tracks/nomad-update-strategies to get rid of some deprecation warnings that started showing up after moving to Nomad 1.0.
> remove deprecation warnings from update-strategies track

- instruqt-tracks/nomad-and-csi-plugins-gcp/deploy-mysql/setup-cloud-client
- instruqt-tracks/nomad-and-csi-plugins-gcp/track.yml
- instruqt-tracks/nomad-and-portworx/deploy-mysql/setup-cloud-client
- instruqt-tracks/nomad-and-portworx/install-portworx/setup-cloud-client
- instruqt-tracks/nomad-and-portworx/track.yml
- instruqt-tracks/nomad-host-volumes/deploy-mysql/setup-nomad-server-1
- instruqt-tracks/nomad-host-volumes/track.yml
Update the 3 stateful storage Instruqt tracks to avoid deprecation warnings related to task-level network stanzas since upgrading to 1.0.
> update stateful storage tracks

- instruqt-tracks/nomad-multi-region-federation/multi-region-deployments/setup-nomad-server-1-east
- instruqt-tracks/nomad-multi-region-federation/multi-region-deployments/setup-nomad-server-1-west
- instruqt-tracks/nomad-multi-region-federation/simulate-failed-deployment/setup-nomad-server-1-east
- instruqt-tracks/nomad-multi-region-federation/simulate-failed-deployment/setup-nomad-server-1-west
- instruqt-tracks/nomad-multi-region-federation/track.yml
This updates the federation Instruqt track network stanzas to avoid deprecation warnings that started in Nomad 1.0. It moves them from tasks to groups.
> update federation network stanzas

- instruqt-tracks/nomad-and-csi-plugins-gcp/track.yml
- instruqt-tracks/nomad-and-portworx/track.yml
- instruqt-tracks/nomad-on-windows/track.yml
Instruqt reported crypto mining on those tracks:
nomad-on-windows
nomad-and-csi-plugins-gcp
nomad-and-portworx
> make tracks with GCP projects private

- instruqt-tracks/nomad-simple-cluster/run-the-server-and-clients/setup-nomad-server
The server name in the track was set to server but the clients were configured to use nomad-server so they did not connect.
> Update the track config to add the correct server name

- instruqt-tracks/nomad-acls/run-the-servers-and-clients/setup-nomad-server-3
- instruqt-tracks/nomad-acls/track.yml
- instruqt-tracks/nomad-host-volumes/config.yml
- instruqt-tracks/nomad-host-volumes/track.yml
- instruqt-tracks/nomad-host-volumes/verify-nomad-cluster-health/setup-nomad-client-1
- instruqt-tracks/nomad-host-volumes/verify-nomad-cluster-health/setup-nomad-client-2
- instruqt-tracks/nomad-host-volumes/verify-nomad-cluster-health/setup-nomad-client-3
- instruqt-tracks/nomad-host-volumes/verify-nomad-cluster-health/setup-nomad-server-1
- instruqt-tracks/nomad-integration-with-vault/verify-agents/setup-hashistack-client-1
- instruqt-tracks/nomad-integration-with-vault/verify-agents/setup-hashistack-client-2
- instruqt-tracks/nomad-integration-with-vault/verify-agents/setup-hashistack-server
- instruqt-tracks/nomad-monitoring/fabio-and-prometheus-jobs/solve-nomad-server
- instruqt-tracks/nomad-monitoring/track.yml
- instruqt-tracks/nomad-multi-region-federation/config.yml
- instruqt-tracks/nomad-multi-region-federation/federation/setup-nomad-client-1-east
- instruqt-tracks/nomad-multi-region-federation/federation/setup-nomad-client-1-west
- instruqt-tracks/nomad-multi-region-federation/federation/setup-nomad-client-2-east
- instruqt-tracks/nomad-multi-region-federation/federation/setup-nomad-client-2-west
- instruqt-tracks/nomad-multi-region-federation/federation/setup-nomad-server-1-east
- instruqt-tracks/nomad-multi-region-federation/federation/setup-nomad-server-1-west
- instruqt-tracks/nomad-multi-region-federation/track.yml
- instruqt-tracks/nomad-multi-server-cluster/automatic-clustering-with-consul/solve-nomad-server-3
- instruqt-tracks/nomad-multi-server-cluster/nomad-and-consul-connect/solve-nomad-server-1
- instruqt-tracks/nomad-multi-server-cluster/track.yml
- instruqt-tracks/nomad-simple-cluster/run-the-server-and-clients/solve-nomad-server
- instruqt-tracks/nomad-simple-cluster/run-your-first-job/solve-nomad-server
- instruqt-tracks/nomad-simple-cluster/track.yml
add some sleeps in solves before new checks
Also change hostname to 127.0.0.1 in CONSUL_HTTP_ADDR for nomad-hosts and nomad-multi-region-federation config.yml files to work around DNS issues caused by recent changes made by Instruqt.
> add some sleeps in solves before new checks

- instruqt-tracks/nomad-multi-server-cluster/automatic-clustering-with-consul/setup-nomad-client-1
- instruqt-tracks/nomad-multi-server-cluster/automatic-clustering-with-consul/setup-nomad-client-2
- instruqt-tracks/nomad-multi-server-cluster/automatic-clustering-with-consul/setup-nomad-server-1
- instruqt-tracks/nomad-multi-server-cluster/automatic-clustering-with-consul/setup-nomad-server-2
- instruqt-tracks/nomad-multi-server-cluster/automatic-clustering-with-consul/setup-nomad-server-3
By setting client_addr to use ens4 (in this case) we set the client to be bound to the local ip and not to the loopback address.   This makes commands like consul members fail which also makes the step joining nomad cluster using consul fail as well as they cannot access the local api/client (127.0.0.1:8500).
By removing this stanza it will default to bind to the loopback address.
https://www.consul.io/docs/agent/options#_client
> client addr on consul server and client set to local IP

- instruqt-tracks/nomad-acls/config.yml
- instruqt-tracks/nomad-basics/config.yml
- instruqt-tracks/nomad-consul-connect/config.yml
- instruqt-tracks/nomad-host-volumes/config.yml
- instruqt-tracks/nomad-integration-with-vault/config.yml
- instruqt-tracks/nomad-job-placement/config.yml
- instruqt-tracks/nomad-monitoring/config.yml
- instruqt-tracks/nomad-multi-server-cluster/config.yml
- instruqt-tracks/nomad-simple-cluster/config.yml
- instruqt-tracks/nomad-update-strategies/config.yml
Update most Nomad workshop tracks to Nomad 1.2.4
The exceptions at this point are the nomad-governance and nomad-federation tracks which use Nomad Enterprise. Updating them would require us to provide students with a Nomad Enterprise license.  Doing that is possible, but needs to be correctly figured out and planned. I will work on that more this week.
> update to Nomad 1.2.4

- instruqt-tracks/nomad-update-strategies/blue-green-deployment/check-nomad-server-1
- instruqt-tracks/nomad-update-strategies/blue-green-deployment/solve-nomad-server-1
- instruqt-tracks/nomad-update-strategies/canary-deployment/check-nomad-server-1
- instruqt-tracks/nomad-update-strategies/canary-deployment/solve-nomad-server-1
- instruqt-tracks/nomad-update-strategies/deploy-the-jobs/check-nomad-server-1
- instruqt-tracks/nomad-update-strategies/deploy-the-jobs/solve-nomad-server-1
- instruqt-tracks/nomad-update-strategies/rolling-update/check-nomad-server-1
- instruqt-tracks/nomad-update-strategies/rolling-update/solve-nomad-server-1
- instruqt-tracks/nomad-update-strategies/track.yml
Fix the nomad-update-strategies track by adding `-detach` to `nomad job run` commands to prevent those commands from entering permanent monitor state when waiting for canaries to be promoted or failed.
> fix nomad-update-strategies track

- .github/workflows/nightly-test.yml
Removed nightly test for nomad-and-portworx track.
> VCDL-608 removing nightly test
